import { NextResponse } from "next/server";
import { and, eq, desc, inArray } from "drizzle-orm";
import { getSession } from "@/lib/auth";
import { hasPermission } from "@/lib/permissions";
import { db } from "@/db";
import { qualityScores, users } from "@/db/schema";
import { logActivity } from "@/services/activity/activity.service";
export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!db)return NextResponse.json({scores:[]});if(!(s.role==="SUPER_ADMIN"||await hasPermission(s,"quality.view")))return NextResponse.json({error:"Forbidden"},{status:403});let ids:string[]=[s.id];if(s.role==="SUPER_ADMIN"||s.role==="HR_MANAGER")ids=(await db.select({id:users.id}).from(users).where(eq(users.organizationId,s.organizationId))).map(x=>x.id);else if(s.role==="MANAGER")ids=[s.id,...(await db.select({id:users.id}).from(users).where(and(eq(users.organizationId,s.organizationId),eq(users.reportingManagerId,s.id)))).map(x=>x.id)];const rows=await db.select({score:qualityScores,userName:users.name}).from(qualityScores).innerJoin(users,eq(users.id,qualityScores.userId)).where(and(eq(qualityScores.organizationId,s.organizationId),inArray(qualityScores.userId,ids))).orderBy(desc(qualityScores.createdAt));return NextResponse.json({scores:rows});}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!db)return NextResponse.json({error:"Database not configured"},{status:500});if(!(s.role==="SUPER_ADMIN"||await hasPermission(s,"quality.score")))return NextResponse.json({error:"Forbidden"},{status:403});const b=await req.json().catch(()=>null);if(!b?.userId||!b?.category||typeof b.score!=="number"||b.score<0||b.score>100||!b.period)return NextResponse.json({error:"userId, category, score (0-100), period required"},{status:422});const [target]=await db.select({id:users.id}).from(users).where(and(eq(users.id,b.userId),eq(users.organizationId,s.organizationId)));if(!target)return NextResponse.json({error:"Employee not found"},{status:404});const [created]=await db.insert(qualityScores).values({organizationId:s.organizationId,userId:b.userId,scoredBy:s.id,category:b.category,score:b.score,period:b.period,comment:b.comment??null}).returning();await logActivity({organizationId:s.organizationId,userId:s.id,action:"QUALITY_SCORED",entityType:"quality_score",entityId:created.id,metadata:{employeeId:b.userId,score:b.score,category:b.category,period:b.period}});return NextResponse.json({score:created},{status:201});}
