"use client";
import { use, useEffect, useState } from "react";
import Link from "next/link";

type Data = { person:any; metrics:any; tasks:any[]; dailyUpdates:any[]; leave:any[]; warnings:any[]; quality:any[]; attendance:any[]; events:any[]; meetings:any[]; activity:any[] };

export default function Employee360({params}:{params:Promise<{id:string}>}){
 const {id}=use(params); const [d,setD]=useState<Data|null>(null); const [error,setError]=useState(""); const [busy,setBusy]=useState("");
 async function load(){const r=await fetch(`/api/management/employee/${id}`,{cache:"no-store"}); const j=await r.json(); if(!r.ok){setError(j.error||"Unable to load");return} setD(j)}
 useEffect(()=>{load()},[id]);
 async function review(updateId:string){setBusy(updateId);const r=await fetch('/api/daily-updates/review',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({updateId,action:'REVIEW'})});setBusy("");if(r.ok)load();else alert((await r.json()).error||'Unable to review')}
 async function leaveDecision(request:any,status:string){setBusy(request.id);const r=await fetch('/api/leave',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:request.id,status,note:status==='REJECTED'?'Rejected from Employee 360':'Approved from Employee 360'})});setBusy("");if(r.ok)load();else alert((await r.json()).error||'Unable to update leave')}
 async function score(){const value=window.prompt('Overall score (0-100)'); if(value===null)return; const score=Number(value); if(!Number.isFinite(score)||score<0||score>100)return alert('Enter a number from 0 to 100.'); setBusy('score');const r=await fetch('/api/quality',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:id,category:'OVERALL',score,period:new Date().toISOString().slice(0,7),comment:'Scored from Employee 360'})});setBusy("");if(r.ok)load();else alert((await r.json()).error||'Unable to score')}
 if(error)return <div className="card p-6 text-red-700">{error}</div>; if(!d)return <div className="h-64 animate-pulse rounded-2xl bg-gray-100"/>;
 const p=d.person,m=d.metrics;
 return <div className="space-y-6"><Link href="/management" className="text-sm text-gray-500 hover:text-gray-800">← Management Control Center</Link>
  <header className="card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-semibold uppercase tracking-wide text-gray-400">Employee 360°</div><h1 className="mt-1 text-2xl font-bold">{p.name}</h1><p className="text-sm text-gray-500">{p.designation||p.role.replace(/_/g,' ')} · {p.employeeCode||'No employee ID'}</p></div><div className="flex gap-2"><button onClick={score} disabled={!!busy} className="rounded-xl bg-gray-900 px-4 py-2 text-sm font-semibold text-white">{busy==='score'?'Saving…':'Score performance'}</button><Link href={`/people/${id}`} className="rounded-xl border px-4 py-2 text-sm font-semibold">Profile</Link></div></div>
   <div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-6">{[['Quality',m.avgQuality+'/100'],['Updates',m.submittedUpdates],['Present days',m.presentDays],['Overdue',m.overdueTasks],['Warnings',m.openWarnings],['Pending leave',m.pendingLeave]].map(x=><div className="rounded-2xl bg-gray-50 p-4" key={x[0] as string}><div className="text-xl font-bold">{x[1]}</div><div className="text-xs text-gray-500">{x[0]}</div></div>)}</div></header>
  <div className="grid gap-5 lg:grid-cols-2">
   <Section title="Tasks"><List items={d.tasks} empty="No tasks"><>{d.tasks.slice(0,8).map(t=><div className="flex items-center justify-between border-b py-3" key={t.id}><div><div className="font-medium">{t.title}</div><div className="text-xs text-gray-500">{t.status} · {t.priority}</div></div><Link href={`/tasks/${t.id}`} className="text-xs font-semibold">Open</Link></div>)}</></List></Section>
   <Section title="Daily updates"><List items={d.dailyUpdates} empty="No updates"><>{d.dailyUpdates.slice(0,8).map(u=><div className="flex items-center justify-between border-b py-3" key={u.id}><div><div className="font-medium">{u.updateDate}</div><div className="text-xs text-gray-500">{u.status}</div></div>{u.status!=='REVIEWED'&&<button onClick={()=>review(u.id)} disabled={!!busy} className="text-xs font-semibold">{busy===u.id?'…':'Review'}</button>}</div>)}</></List></Section>
   <Section title="Leave requests"><List items={d.leave} empty="No leave requests"><>{d.leave.slice(0,8).map(x=><div className="flex items-center justify-between border-b py-3" key={x.id}><div><div className="font-medium">{x.type} · {x.status}</div><div className="text-xs text-gray-500">{x.startDate} → {x.endDate}</div></div>{x.status==='PENDING'&&<div className="flex gap-2"><button onClick={()=>leaveDecision(x,'APPROVED')} className="text-xs font-semibold">Approve</button><button onClick={()=>leaveDecision(x,'REJECTED')} className="text-xs font-semibold text-red-700">Reject</button></div>}</div>)}</></List></Section>
   <Section title="Warnings"><List items={d.warnings} empty="No warnings"><>{d.warnings.slice(0,8).map(w=><div className="border-b py-3" key={w.id}><div className="font-medium">{w.type} · {w.status}</div><div className="mt-1 text-sm text-gray-600">{w.reason}</div></div>)}</></List></Section>
   <Section title="Quality history"><List items={d.quality} empty="No scores"><>{d.quality.slice(0,8).map(q=><div className="flex justify-between border-b py-3" key={q.id}><div><div className="font-medium">{q.category.replace(/_/g,' ')}</div><div className="text-xs text-gray-500">{q.period}</div></div><strong>{q.score}/100</strong></div>)}</></List></Section>
   <Section title="Recent attendance"><List items={d.attendance} empty="No attendance"><>{d.attendance.slice(0,8).map(a=><div className="flex justify-between border-b py-3" key={a.id}><span>{a.attendanceDate}</span><span className="font-semibold">{a.status}</span></div>)}</></List></Section>
  </div>
 </div>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="card p-5"><h2 className="font-bold">{title}</h2>{children}</section>}
function List({items,empty,children}:{items:any[];empty:string;children:React.ReactNode}){return items.length?<div className="mt-3">{children}</div>:<p className="mt-3 text-sm text-gray-500">{empty}</p>}
