"use client";
import { useEffect,useMemo,useState } from "react";

type Person={id:string;name:string;email:string;role:string;employeeCode?:string|null;status?:string};
type Conversation={id:string;type:"DIRECT"|"GROUP"|"SPACE";name:string|null;description:string|null;unreadCount:number;memberCount:number;members:{id:string;name:string;email:string;role:string}[]};
type Message={id:string;body:string;senderId:string;senderName:string;createdAt:string;type:string};

export default function ChatPage(){
 const [convs,setConvs]=useState<Conversation[]>([]),[active,setActive]=useState(""),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(""),[people,setPeople]=useState<Person[]>([]),[meId,setMeId]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[compose,setCompose]=useState(false),[kind,setKind]=useState<"DIRECT"|"GROUP"|"SPACE">("DIRECT"),[name,setName]=useState(""),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState("");
 const current=useMemo(()=>convs.find(c=>c.id===active),[convs,active]);
 async function load(){setLoading(true);const r=await fetch('/api/chat/conversations',{cache:'no-store'});const d=await r.json();if(r.ok){const c=d.conversations||[];setConvs(c);if(!active&&c[0])setActive(c[0].id)}setLoading(false)}
 async function loadPeople(){const r=await fetch('/api/people?status=ACTIVE',{cache:'no-store'});const d=await r.json();if(r.ok)setPeople(d.people||[])}
 async function loadMessages(id:string){const r=await fetch(`/api/chat/conversations/${id}/messages`,{cache:'no-store'});const d=await r.json();if(r.ok)setMessages(d.messages||[]);}
 useEffect(()=>{load();loadPeople();fetch('/api/auth/me').then(r=>r.json()).then(d=>setMeId(d.user?.id||''))},[]); useEffect(()=>{if(!active)return;loadMessages(active);const t=setInterval(()=>loadMessages(active),5000);return()=>clearInterval(t)},[active]);
 async function send(){if(!text.trim()||!active||busy)return;setBusy(true);const r=await fetch(`/api/chat/conversations/${active}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'TEXT',body:text.trim()})});const d=await r.json();if(r.ok){setText('');await loadMessages(active);await load()}else setError(d.error||'Unable to send');setBusy(false)}
 async function create(){setError("");if(!selected.length){setError('Select at least one person.');return}if(kind==='DIRECT'&&selected.length!==1){setError('Direct chat needs exactly one person.');return}if((kind==='GROUP'||kind==='SPACE')&&selected.length<1){setError('Select members.');return}const r=await fetch('/api/chat/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:kind,name:name.trim()||undefined,memberIds:selected})});const d=await r.json();if(!r.ok){setError(d.error||'Unable to create conversation');return}setCompose(false);setSelected([]);setName('');await load();setActive(d.conversation.id);}
 return <div className="grid min-h-[calc(100vh-120px)] gap-4 lg:grid-cols-[360px_1fr]">
  <section className="card overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><h1 className="text-xl font-bold">Chats</h1><p className="text-sm text-gray-500">Direct, group and team spaces</p></div><button onClick={()=>setCompose(true)} className="rounded-xl bg-gray-900 px-3 py-2 text-sm font-semibold text-white">+ New</button></div><div className="divide-y">{loading?<div className="p-5 text-gray-500">Loading…</div>:convs.map(c=><button key={c.id} onClick={()=>setActive(c.id)} className={`w-full p-4 text-left hover:bg-gray-50 ${active===c.id?'bg-gray-100':''}`}><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-gray-900 text-sm font-bold text-white">{(c.name||c.members[0]?.name||c.type).slice(0,1).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="truncate font-semibold">{c.name||c.members.map(m=>m.name).join(', ')||'Conversation'}</div><div className="mt-1 text-xs text-gray-500">{c.type} · {c.memberCount} member{c.memberCount===1?'':'s'}</div></div>{c.unreadCount>0&&<span className="rounded-full bg-gray-900 px-2 py-0.5 text-xs font-bold text-white">{c.unreadCount}</span>}</div></button>)}{!loading&&!convs.length&&<div className="p-6"><div className="text-sm text-gray-500">No conversations yet.</div><div className="mt-4 space-y-2">{people.filter(p=>p.status==='ACTIVE' && p.id!==meId).slice(0,6).map(p=><button key={p.id} onClick={()=>{setKind('DIRECT');setSelected([p.id]);setCompose(true)}} className="flex w-full items-center gap-3 rounded-xl border p-3 text-left hover:bg-gray-50"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-gray-900 text-xs font-bold text-white">{p.name.slice(0,1).toUpperCase()}</div><div><div className="text-sm font-semibold">{p.name}</div><div className="text-xs text-gray-500">{p.employeeCode||p.email}</div></div></button>)}</div></div>}</div></section>
  <section className="card flex min-h-[600px] flex-col overflow-hidden"><div className="border-b p-5"><div className="font-bold">{current?.name||current?.members.map(m=>m.name).join(', ')||'Select a conversation'}</div><div className="mt-1 text-xs text-gray-500">{current?.type}{current?` · ${current.memberCount} members`:''}</div></div><div className="flex-1 space-y-3 overflow-y-auto bg-gray-50/50 p-5">{messages.map(m=><div key={m.id} className={`flex ${m.senderId===meId?'justify-end':'justify-start'}`}><div className={`max-w-[78%] rounded-2xl px-4 py-3 ${m.senderId===meId?'bg-gray-900 text-white':'bg-white border'}`}><div className="mb-1 text-[11px] font-semibold opacity-60">{m.senderName}</div><div className="text-sm whitespace-pre-wrap">{m.body}</div><div className="mt-1 text-[10px] opacity-50">{new Date(m.createdAt).toLocaleString()}</div></div></div>)}{active&&!messages.length&&<div className="py-20 text-center text-sm text-gray-400">No messages yet. Say hello.</div>}</div><div className="border-t p-4"><div className="flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} disabled={!active} placeholder="Write a message…" className="flex-1 rounded-xl border bg-white px-4 py-3 outline-none focus:ring-2 focus:ring-gray-900/10"/><button onClick={send} disabled={!active||busy} className="rounded-xl bg-gray-900 px-5 font-semibold text-white disabled:opacity-40">Send</button></div></div></section>
  {compose&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">New conversation</h2><button onClick={()=>setCompose(false)} className="text-gray-400">✕</button></div><div className="mt-5 grid gap-4"><div className="flex gap-2">{(['DIRECT','GROUP','SPACE'] as const).map(k=><button key={k} onClick={()=>{setKind(k);setSelected([])}} className={`rounded-xl px-3 py-2 text-xs font-semibold ${kind===k?'bg-gray-900 text-white':'bg-gray-100'}`}>{k}</button>)}</div>{kind!=='DIRECT'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Conversation name" className="rounded-xl border px-3 py-2.5"/>}<div className="max-h-64 space-y-1 overflow-y-auto rounded-xl border p-2">{people.filter(p=>p.status==='ACTIVE' && p.id!==meId).map(p=><label key={p.id} className="flex cursor-pointer items-center gap-3 rounded-lg p-2 hover:bg-gray-50"><input type={kind==='DIRECT'?'radio':'checkbox'} name="member" checked={selected.includes(p.id)} onChange={()=>setSelected(x=>kind==='DIRECT'?[p.id]:x.includes(p.id)?x.filter(id=>id!==p.id):[...x,p.id])}/><div><div className="text-sm font-semibold">{p.name}</div><div className="text-xs text-gray-500">{p.employeeCode||p.email} · {p.role}</div></div></label>)}</div>{error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="flex justify-end gap-2"><button onClick={()=>setCompose(false)} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Cancel</button><button onClick={create} className="rounded-xl bg-gray-900 px-4 py-2.5 text-sm font-semibold text-white">Create</button></div></div></div></div>}
 </div>
}
